import type { Locale } from "@/lib/i18n";

const en = {
  common: { retry: "Retry", demo: "Open sample demo", cancel: "Cancel", role: "Role", stack: "Stack", model: "AI model", notSelected: "Not selected" },
  pages: { errorTitle: "Something went off-script.", errorBody: "Your work is still here. Try loading this screen again.", tryAgain: "Try again", notFoundCode: "404 · TICKET NOT FOUND", notFoundTitle: "This task is not on the board.", notFoundBody: "The page may have moved, or the link may be incomplete.", backHome: "Back home", loading: "Loading JuniorFlow AI" },  history: { loading: "Loading browser history…", search: "Search tickets", placeholder: "Title, ID, role, or technology…", status: "Status", all: "All statuses", ticket: "ticket", tickets: "tickets", clearAll: "Clear all", open: "Open", stack: "Profile stack", noMatch: "No tickets match your filters", empty: "No saved tickets yet", try: "Try a different search or status.", emptyBody: "Generate a real ticket and it will be saved here automatically.", clearFilters: "Clear filters", create: "Create first ticket", local: "History stays in this browser only. No account or database is used.", storage: "Browser storage is unavailable. Enable local storage to persist your tickets.", recovered: "Corrupted history data was isolated and the page recovered with an empty history.", deleteOne: "Delete ‘{title}’ from your history?", deleteAll: "Delete every saved ticket and review? This cannot be undone.", deleteAria: "Delete {title}" },  profile: { roleDescriptions: { "Front-End": "Interfaces and web experiences", "Back-End": "APIs, data, and services", "Full-Stack": "End-to-end product work", Mobile: "iOS and Android apps" }, customHelp: "Add technologies that are not listed above, separated by commas.", customPlaceholder: "e.g. Docker, Redis, GraphQL", customInvalid: "Check other technologies.", customLimit: "Add no more than five custom technologies.", techRequired: "Choose or add at least one technology.", chars: "20–800 characters", unavailable: "Ticket generation unavailable", creating: "GPT-5.6 is creating…", guidedDescription: "A project-management dashboard for small remote teams. Users can create projects, invite teammates, and track tasks." },
  session: { history: "History", status: "Status", stack: "Profile stack", submission: "Submission type", saved: "Last saved", storage: "This update could not be saved in browser storage. Keep this page open and check your browser privacy settings.", ticketLanguage: "Ticket language", mismatch: "This ticket was generated in {language}. Changing the interface language does not translate saved AI content." },
  ticket: { sample: "SAMPLE TICKET / DEMO MODE", priority: "Priority", difficulty: "Difficulty", estimated: "Estimated", context: "Company context", problem: "The problem", objective: "Objective", requirements: "Requirements", acceptance: "Acceptance criteria", technologies: "Technologies", files: "Likely files to modify", hint: "Starting hint", mistakes: "Common mistakes" },
  solution: { eyebrow: "Your solution", title: "Walk your senior through it.", intro: "The reasoning matters as much as the final code.", locked: "This reviewed submission is locked until you choose to edit it.", approach: "Your approach", approachHelp: "Describe the reasoning, steps, and choices you would use to solve the ticket.", approachPlaceholder: "Explain how you would investigate and solve the ticket…", type: "Submission type", planHelp: "Pseudocode / technical plan is a clear plan that does not need to compile. Working code is concrete code reviewed more strictly.", code: "Code or pseudocode", codePlaceholder: "// Paste code or write clear pseudocode here", difficult: "What was difficult?", difficultHelp: "Describe the doubts, blockers, or decisions you were unsure about.", difficultPlaceholder: "Tell your senior where you felt unsure…", question: "Question for your senior", questionHelp: "Ask one specific technical question where you want guidance.", questionPlaceholder: "What would you like clarified?", unavailable: "Review unavailable", complete: "Review completed", edit: "Edit submission", reviewing: "GPT-5.6 is reviewing…", request: "Request senior review", duplicate: "This submission already has a completed review. Choose Edit submission before requesting another review.", changed: "Change the submission before requesting a new review.", invalid: "Check your submission.", editTitle: "Edit this submission?", editDescription: "Editing will remove the current senior review. Your ticket, profile, and submitted text will be kept.", remove: "Remove review and edit" },
  review: { eyebrow: "Senior review", demo: " · Sample / Demo mode", ready: "Your review is ready.", aria: "Senior review sections", tabs: { overview: "Overview", strengths: "Strengths & priorities", technical: "Technical review", acceptance: "Acceptance criteria", learning: "Learning plan" }, score: "Overall score", summary: "Review summary", strengths: "Top strengths", improvements: "Improvement priorities", problems: "Problems", bugs: "Possible bugs", security: "Security", readability: "Readability assessment", acceptance: "Acceptance criteria", education: "Educational explanation", ideal: "Ideal solution, in short", next: "Recommended next ticket", skills: "Skills to study next", emptyStrengths: "No specific strengths were identified.", emptyImprovements: "No immediate improvements were identified.", emptyProblems: "No material problems identified.", emptyBugs: "No likely bugs identified.", emptySecurity: "No specific security concerns identified.", emptyAcceptance: "No acceptance-criteria assessment is available.", emptySkills: "No study topics were suggested." },
  demo: { label: "Sample ticket / Demo mode.", body: "This ticket and review are static sample data and never call the OpenAI API.", back: "Back to profile", solution: "Sample solution · Demo mode", title: "Walk your senior through it.", static: "This form returns a static sample review and never calls the API.", loading: "Loading sample review…", show: "Show sample review", privacy: "Sample ticket / Demo mode — no data is sent to OpenAI." },
  errors: { INVALID_INPUT: "Check the information you entered and try again.", ACCESS_REQUIRED: "Unlock the AI demo before using this feature.", RATE_LIMITED: "Too many requests. Wait a moment and try again.", TIMEOUT: "The request timed out. Please retry.", NETWORK_ERROR: "The network request failed. Check your connection and retry.", DUPLICATE_REVIEW: "This submission already has a completed review.", STORAGE_UNAVAILABLE: "Browser storage is unavailable. Check your privacy settings and retry.", default: "The request could not be completed. Please retry." },
} as const;

type DeepStringify<T> = { readonly [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]> };
type CopyShape = DeepStringify<typeof en>;
const it: CopyShape = {
  common: { retry: "Riprova", demo: "Apri la demo di esempio", cancel: "Annulla", role: "Ruolo", stack: "Stack", model: "Modello AI", notSelected: "Non selezionato" },
  pages: { errorTitle: "Qualcosa è andato fuori copione.", errorBody: "Il tuo lavoro è ancora qui. Prova a ricaricare questa schermata.", tryAgain: "Riprova", notFoundCode: "404 · TICKET NON TROVATO", notFoundTitle: "Questa attività non è nella bacheca.", notFoundBody: "La pagina potrebbe essere stata spostata o il link potrebbe essere incompleto.", backHome: "Torna alla home", loading: "Caricamento di JuniorFlow AI" },  history: { loading: "Caricamento dello storico locale…", search: "Cerca ticket", placeholder: "Titolo, ID, ruolo o tecnologia…", status: "Stato", all: "Tutti gli stati", ticket: "ticket", tickets: "ticket", clearAll: "Cancella tutto", open: "Apri", stack: "Stack del profilo", noMatch: "Nessun ticket corrisponde ai filtri", empty: "Nessun ticket salvato", try: "Prova una ricerca o uno stato diverso.", emptyBody: "Genera un ticket reale e verrà salvato automaticamente qui.", clearFilters: "Azzera filtri", create: "Crea il primo ticket", local: "Lo storico resta soltanto in questo browser. Non vengono usati account o database.", storage: "Lo spazio di archiviazione del browser non è disponibile. Abilitalo per conservare i ticket.", recovered: "I dati danneggiati sono stati isolati e la pagina è stata ripristinata con uno storico vuoto.", deleteOne: "Eliminare ‘{title}’ dallo storico?", deleteAll: "Eliminare tutti i ticket e le review salvati? L'azione non può essere annullata.", deleteAria: "Elimina {title}" },  profile: { roleDescriptions: { "Front-End": "Interfacce ed esperienze web", "Back-End": "API, dati e servizi", "Full-Stack": "Sviluppo completo del prodotto", Mobile: "App iOS e Android" }, customHelp: "Aggiungi le tecnologie non presenti sopra, separate da virgole.", customPlaceholder: "es. Docker, Redis, GraphQL", customInvalid: "Controlla le altre tecnologie.", customLimit: "Aggiungi al massimo cinque tecnologie personalizzate.", techRequired: "Scegli o aggiungi almeno una tecnologia.", chars: "20–800 caratteri", unavailable: "Generazione del ticket non disponibile", creating: "GPT-5.6 sta creando…", guidedDescription: "Una dashboard di gestione progetti per piccoli team da remoto. Gli utenti possono creare progetti, invitare colleghi e monitorare attività." },
  session: { history: "Storico", status: "Stato", stack: "Stack del profilo", submission: "Tipo di consegna", saved: "Ultimo salvataggio", storage: "Non è stato possibile salvare questo aggiornamento nel browser. Mantieni aperta la pagina e controlla le impostazioni sulla privacy.", ticketLanguage: "Lingua del ticket", mismatch: "Questo ticket è stato generato in {language}. La lingua dell’interfaccia non modifica i contenuti AI già salvati." },
  ticket: { sample: "TICKET DI ESEMPIO / MODALITÀ DEMO", priority: "Priorità", difficulty: "Difficoltà", estimated: "Stima", context: "Contesto aziendale", problem: "Il problema", objective: "Obiettivo", requirements: "Requisiti", acceptance: "Criteri di accettazione", technologies: "Tecnologie", files: "File che potresti modificare", hint: "Suggerimento iniziale", mistakes: "Errori comuni" },
  solution: { eyebrow: "La tua soluzione", title: "Illustrala al tuo senior.", intro: "Il ragionamento conta quanto il codice finale.", locked: "Questa consegna revisionata è bloccata finché non scegli di modificarla.", approach: "Il tuo approccio", approachHelp: "Descrivi il ragionamento, i passaggi e le scelte con cui risolveresti il ticket.", approachPlaceholder: "Spiega come analizzeresti e risolveresti il ticket…", type: "Tipo di consegna", planHelp: "Pseudocodice / piano tecnico è un piano chiaro che non deve compilare. Il codice funzionante è un’implementazione concreta valutata più severamente.", code: "Codice o pseudocodice", codePlaceholder: "// Incolla il codice o scrivi uno pseudocodice chiaro", difficult: "Cosa è stato difficile?", difficultHelp: "Descrivi dubbi, ostacoli o decisioni su cui non eri sicuro.", difficultPlaceholder: "Indica al senior dove ti sei sentito insicuro…", question: "Domanda per il senior", questionHelp: "Fai una domanda tecnica specifica su cui desideri aiuto.", questionPlaceholder: "Che cosa vorresti chiarire?", unavailable: "Review non disponibile", complete: "Review completata", edit: "Modifica consegna", reviewing: "GPT-5.6 sta revisionando…", request: "Richiedi la review del senior", duplicate: "Questa consegna ha già una review completata. Scegli Modifica consegna prima di richiederne un’altra.", changed: "Modifica la consegna prima di richiedere una nuova review.", invalid: "Controlla la consegna.", editTitle: "Modificare questa consegna?", editDescription: "La modifica rimuoverà la review corrente. Ticket, profilo e testo inviato verranno mantenuti.", remove: "Rimuovi la review e modifica" },
  review: { eyebrow: "Review del senior", demo: " · Esempio / Modalità demo", ready: "La tua review è pronta.", aria: "Sezioni della review del senior", tabs: { overview: "Panoramica", strengths: "Punti forti e priorità", technical: "Revisione tecnica", acceptance: "Criteri di accettazione", learning: "Piano di apprendimento" }, score: "Punteggio complessivo", summary: "Sintesi della review", strengths: "Punti di forza principali", improvements: "Priorità di miglioramento", problems: "Problemi", bugs: "Bug possibili", security: "Sicurezza", readability: "Valutazione della leggibilità", acceptance: "Criteri di accettazione", education: "Spiegazione educativa", ideal: "Soluzione ideale in breve", next: "Prossimo ticket consigliato", skills: "Competenze da studiare", emptyStrengths: "Non sono stati individuati punti di forza specifici.", emptyImprovements: "Non sono stati individuati miglioramenti immediati.", emptyProblems: "Non sono stati individuati problemi rilevanti.", emptyBugs: "Non sono stati individuati bug probabili.", emptySecurity: "Non sono stati individuati problemi di sicurezza specifici.", emptyAcceptance: "Non è disponibile una valutazione dei criteri di accettazione.", emptySkills: "Non sono stati suggeriti argomenti di studio." },
  demo: { label: "Ticket di esempio / Modalità demo.", body: "Questo ticket e la review sono dati statici e non chiamano mai l’API OpenAI.", back: "Torna al profilo", solution: "Soluzione di esempio · Modalità demo", title: "Illustrala al tuo senior.", static: "Questo modulo restituisce una review statica e non chiama mai l’API.", loading: "Caricamento review di esempio…", show: "Mostra review di esempio", privacy: "Ticket di esempio / Modalità demo — nessun dato viene inviato a OpenAI." },
  errors: { INVALID_INPUT: "Controlla le informazioni inserite e riprova.", ACCESS_REQUIRED: "Sblocca la demo AI prima di usare questa funzione.", RATE_LIMITED: "Troppe richieste. Attendi un momento e riprova.", TIMEOUT: "La richiesta è scaduta. Riprova.", NETWORK_ERROR: "Richiesta di rete non riuscita. Controlla la connessione e riprova.", DUPLICATE_REVIEW: "Questa consegna ha già una review completata.", STORAGE_UNAVAILABLE: "Lo spazio di archiviazione del browser non è disponibile. Controlla le impostazioni sulla privacy e riprova.", default: "Non è stato possibile completare la richiesta. Riprova." },
};

export const UI_COPY: Record<Locale, CopyShape> = { en, it };
export function localizedApiError(code: string, locale: Locale) {
  const errors = UI_COPY[locale].errors as Record<string, string>;
  return errors[code] ?? errors.default;
}
